### ISSUE TITLE
Crash upon continuing

### ISSUE THREAD

**Issue by Ordinaryperson2** [cloveranon/Clover-Edition#121]
I often get this crash upon continuing, maybe more commonly when I use the model I'm training but it's happened on the base one too. Not 100% sure on how to reproduce it, but the crash save preserves the bug (so putting new actions in is fine, but this save is cursed to crash if you ever continue again). Maybe it's got something to do with the AI generating > or newlines? I thought it was more about some sequence of /retry and /alter earlier, but there was no /alter and only 1 /retry involved this time.
Here's my most recent broken save:
```
{"temp": 0.4, "top-p": 0.925, "top-keks": 50, "rep-pen": 1.25, "context": "", "memory": [], "actions": ["City Crossroad Bustling pedestrians surround you, travelling to and from the various businesses. To the south lies a park. To the north is a bank. Angela follows you eagerly.", "You ask Angela about the park.", "You look at the newspaper.", "You ask Angela about the World Government.", "You look at the trees."], "results": ["> You go east. You walk into the park. Park The park is fairly large, with trees on all sides. The path leads west through a grove of trees towards a small fountain.", "She tells you that it's in a good location for children to play. There are also benches here where people can sit and read or watch the world go by. You see an old man sitting nearby reading the newspaper.", "It says that the World Government has declared war on the Earth Federation! \"What?\" you say. \"That doesn't sound right\". Angela looks surprised.", "\"The World Government? They're just another government\", she replies. \"They have their own laws and regulations too\". She continues to explain how they work, and what they want you to do.", "You ask Angela about the trees. \"I don't know much about this,\" she says. \"But I think they're called 'emerald trees'\". You ask Angela about the emerald trees."]}
```

And here's the error:
```
Traceback (most recent call last):
  File "play.py", line 755, in <module>
    gm.play_story()
  File "play.py", line 740, in play_story
    if self.process_action(action, suggested_actions):  # End of story
  File "play.py", line 666, in process_action
    result = self.story.act(action)
  File "D:\Users\Poke\Downloads\coldcut-win-x64\system\repos\CloverEdition\storymanager.py", line 21, in act
    assert (self.context.strip() + action.strip())
AssertionError

A fatal error has occurred.

Successfully saved to crashes/04-02-2020_190812
```

**Comment by Ordinaryperson2** [comment]
Removing the assert seems to work fine, still runs and keeps up with what I'm saying after a continue. No idea if it's somehow fucked on the inside.

**Comment by MikkoMMM** [comment]
I can affirm this savefile causing crashes on my end. In the newest version of master, the error is:
```
> You

Continuing...
Traceback (most recent call last):
  File "play.py", line 758, in <module>
    gm.play_story()
  File "play.py", line 739, in play_story
    if self.process_action(action, suggested_actions):  # End of story
  File "play.py", line 668, in process_action
    result = self.story.act(action)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/storymanager.py", line 21, in act
    assert (self.context.strip() + action.strip())
AssertionError

A fatal error has occurred.
```

I think what is happening is that on the line `assert (self.context.strip() + action.strip())`, both context.strip() and action.strip() produce strings of zero-length so it becomes assert("") which causes a crash.

My belief is that that assertion is there to avoid such a scenario where the generator is passed completely empty arguments. It seems very bad user-friendliness-wise, though, and I didn't get crashes when I removed the assert. Though, passing "" directly as the first or second argument of self.generator.generate crashes it; I'm not sure what's so different with that.

**Comment by MikkoMMM** [comment]
There are still occasions when the game crashes with this AssertionError. I had input an empty context, my prompt was:
```
You ask the AI to tell you a knock knock joke.

The AI says: "
```

After the reply, I just hit Enter with the default > You. Then it crashed. Maybe this helps figuring these crashes out, assuming it's from the same bug of course.
