### ISSUE TITLE
Any way to increase allowed memory size?

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#126]
Now that I have a decent GPU to play this game on, I've tried to play a bit more again. Short "factual" statements in the context didn't seem to give me the kind of results I was hoping for, so I'm trying to go for a long form context and initial prompt to give the AI examples of what kind of text I am expecting it to generate. Kind of a middle ground between having to generate my own model entirely and being very much at the whims of the very broad default model. Of course, I'm not even sure if it would work like that and maybe that much memory might interfere with coherent story progression. But still. If one were to want to have a ridiculously long context or whatever, is there a way? Right now it crashes (and I'm not sure but that doesn't look like it's from my GPU running out of memory):

```
02/19/2020 23:58:28 - ERROR - CONTEXT IS TOO LONG ERROR
Traceback (most recent call last):
  File "play.py", line 758, in <module>
    gm.play_story()
  File "play.py", line 697, in play_story
    if not self.init_story():  # Failed init
  File "play.py", line 423, in init_story
    self.story = new_story(self.generator, self.context, self.prompt)
  File "play.py", line 211, in new_story
    story.act(prompt)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/storymanager.py", line 29, in act
    repetition_penalty=settings.getfloat('rep-pen'))
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 335, in generate
    stop_tokens=self.tokenizer.encode(["<|endoftext|>", ">"])
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 303, in generate_raw
    stop_tokens=stop_tokens,
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 245, in sample_sequence
    tokenizer=self.tokenizer
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 128, in sample_sequence
    logits, pasts = model(input_ids=input_ids_next, past=pasts)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 171, in forward
    hidden_states, pasts = self.transformer(input_ids, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 144, in forward
    hidden_states = inputs_embeds + position_embeds
RuntimeError: The size of tensor a (2005) must match the size of tensor b (1024) at non-singleton dimension 0

A fatal error has occurred. 
```

Just adding a few zeroes to max_history_tokens and maxHistory didn't do the trick.

**Comment by minusplus** [comment]
The limit is built into the model.

**Comment by MikkoMMM** [comment]
Okay, so the answer is "no" (without creating a new model), then.
