### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#128]
I thought this might be because I messed with another Torch program which had slightly different dependencies, but I've `python3.7 -m pip uninstall`ed torch, transformers, and every dependency that `python3.7 -m pip install -r requirements.txt` could find, and then reinstalled them via that command. However, it's still crashing:

```
[mikko@localhost Clover-Edition]$ python3.7 play.py 
...
Generating story...

The world is in a state of a nuclear fallout. You are sent out from your shelter to investigate the condition of the 
Earth.

You leave the shelter. Your surroundings are a barren, irradiated wasteland. You spot some mutated insects and some 
larger animals.
Traceback (most recent call last):
  File "play.py", line 758, in <module>
    gm.play_story()
  File "play.py", line 697, in play_story
    if not self.init_story():  # Failed init
  File "play.py", line 423, in init_story
    self.story = new_story(self.generator, self.context, self.prompt)
  File "play.py", line 211, in new_story
    story.act(prompt)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/storymanager.py", line 29, in act
    repetition_penalty=settings.getfloat('rep-pen'))
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 335, in generate
    stop_tokens=self.tokenizer.encode(["<|endoftext|>", ">"])
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 303, in generate_raw
    stop_tokens=stop_tokens,
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 245, in sample_sequence
    tokenizer=self.tokenizer
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 128, in sample_sequence
    logits, pasts = model(input_ids=input_ids_next, past=pasts)
  File "/home/mikko/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 171, in forward
    hidden_states, pasts = self.transformer(input_ids, **kwargs)
  File "/home/mikko/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 151, in forward
    hidden_states, present = trans_block(hidden_states, layer_past, mask)
  File "/home/mikko/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 109, in forward
    a, present = self.attn(self.ln_1(x), layer_past, mask)
  File "/home/mikko/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 59, in forward
    x = self.c_attn(x)
  File "/home/mikko/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2.py", line 23, in forward
    self._weightT = self.weight.T
AttributeError: 'Parameter' object has no attribute 'T'

A fatal error has occurred. 

code 1

[mikko@localhost Clover-Edition]$ sudo python3.7 -m pip install -r requirements.txt 
Requirement already satisfied: torch in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: transformers==2.3.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.3.0)
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (2.23.0)
Requirement already satisfied: tqdm in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (4.43.0)
Requirement already satisfied: sentencepiece in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (0.1.85)
Requirement already satisfied: boto3 in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (1.12.6)
Requirement already satisfied: numpy in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (1.18.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (2020.2.20)
Requirement already satisfied: sacremoses in /usr/lib/python3.7/site-packages (from transformers==2.3.0->-r requirements.txt (line 2)) (0.0.38)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.7/site-packages (from requests->transformers==2.3.0->-r requirements.txt (line 2)) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.7/site-packages (from requests->transformers==2.3.0->-r requirements.txt (line 2)) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->transformers==2.3.0->-r requirements.txt (line 2)) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->transformers==2.3.0->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: botocore<1.16.0,>=1.15.6 in /usr/lib/python3.7/site-packages (from boto3->transformers==2.3.0->-r requirements.txt (line 2)) (1.15.6)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/lib/python3.7/site-packages (from boto3->transformers==2.3.0->-r requirements.txt (line 2)) (0.3.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/lib/python3.7/site-packages (from boto3->transformers==2.3.0->-r requirements.txt (line 2)) (0.9.4)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from sacremoses->transformers==2.3.0->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: click in /usr/lib/python3.7/site-packages (from sacremoses->transformers==2.3.0->-r requirements.txt (line 2)) (7.0)
Requirement already satisfied: joblib in /usr/lib/python3.7/site-packages (from sacremoses->transformers==2.3.0->-r requirements.txt (line 2)) (0.14.1)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/lib/python3.7/site-packages (from botocore<1.16.0,>=1.15.6->boto3->transformers==2.3.0->-r requirements.txt (line 2)) (0.15.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/lib/python3.7/site-packages (from botocore<1.16.0,>=1.15.6->boto3->transformers==2.3.0->-r requirements.txt (line 2)) (2.8.1)
[mikko@localhost Clover-Edition]$ 
```

**Comment by MikkoMMM** [comment]
I figured it was a wrong Torch version. I even tried to reinstall it without using cache but somehow it's still finding a wrong version on my system:
```
[mikko@localhost Clover-Edition]$ python3.7
Python 3.7.6 (default, Dec 26 2019, 13:40:38) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.1.0
>>> 
```

What's going on?

**Comment by MikkoMMM** [comment]
Okay, I've got it. An old Torch version was installed as a user, to ~/.local/lib/python3.7/site-packages/.
So, after `python3.7 -m pip uninstall torch` without sudo, things started working. A final check for Torch version could be an idea, but then again, I suppose people might find this issue if they are switching between Torch versions themselves.
