### ISSUE TITLE
Crash after selecting model (or when single model available)

### ISSUE THREAD

**Issue by Bookwald** [cloveranon/Clover-Edition#165]
Enter a number from above (default 0):1
05/11/2021 20:26:44 - INFO - Using device=cuda, checkpoint=models\LightNovel, dtype=torch.float16
Can't set hidden_size with value 2560 for GPT2Config {
  "_name_or_path": "EleutherAI/gpt-neo-2.7B",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      16
    ]
  ],
  "bos_token_id": 50256,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "model_type": "gpt2",
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50,
      "temperature": 0.9
    }
  },
  "tokenizer_class": "GPT2Tokenizer",
  "transformers_version": "4.6.0.dev0"
}

Traceback (most recent call last):
  File "C:\Games\Clover-Edition-master\play.py", line 791, in <module>
    gm = GameManager(get_generator())
  File "C:\Games\Clover-Edition-master\play.py", line 64, in get_generator
    generator = GPT2Generator(
  File "C:\Games\Clover-Edition-master\gpt2generator.py", line 256, in __init__
    self.model = model_class.from_pretrained(str(self.checkpoint_path))
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\modeling_utils.py", line 998, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 408, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 513, in from_dict
    config = cls(**config_dict)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\models\gpt2\configuration_gpt2.py", line 156, in __init__
    super().__init__(bos_token_id=bos_token_id, eos_token_id=eos_token_id, **kwargs)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 282, in __init__
    raise err
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 279, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute

A fatal error has occurred.
Traceback (most recent call last):
  File "C:\Games\Clover-Edition-master\play.py", line 791, in <module>
    gm = GameManager(get_generator())
  File "C:\Games\Clover-Edition-master\play.py", line 64, in get_generator
    generator = GPT2Generator(
  File "C:\Games\Clover-Edition-master\gpt2generator.py", line 256, in __init__
    self.model = model_class.from_pretrained(str(self.checkpoint_path))
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\modeling_utils.py", line 998, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 408, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 513, in from_dict
    config = cls(**config_dict)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\models\gpt2\configuration_gpt2.py", line 156, in __init__
    super().__init__(bos_token_id=bos_token_id, eos_token_id=eos_token_id, **kwargs)
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 282, in __init__
    raise err
  File "C:\Games\Clover-Edition-master\venv\Lib\site-packages\transformers\configuration_utils.py", line 279, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Games\Clover-Edition-master\play.py", line 806, in <module>
    if gm and gm.story:
NameError: name 'gm' is not defined

[process exited with code 1]

**Comment by Bookwald** [comment]
I found the problem. Apparently gpt-neo models are highly sensitive to what they are named. When I changed the model folder names to their original name it worked fine! Oddly enough, the older 774M model can have its folder renamed to whatever and still works. aka, I named the model folder "EleutherAI" and it didn't work. I renamed the folder "gpt-neo-2.7B" and I didn't get any errors.

**Comment by Skhmt** [comment]
> I found the problem. Apparently gpt-neo models are highly sensitive to what they are named. When I changed the model folder names to their original name it worked fine! Oddly enough, the older 774M model can have its folder renamed to whatever and still works. aka, I named the model folder "EleutherAI" and it didn't work. I renamed the folder "gpt-neo-2.7B" and I didn't get any errors.

That's really strange.

**Comment by AtaIanta** [comment]
In `gpt2generator.py` there is a code:
```
if "gpt-neo" in str(model_path):
            self.max_history_tokens = 2048 - generate_num
            model_class = GPTNeoForCausalLM
```
So it's not that strange that gpt-neo models needs specific folder name to work. If the folder does not have `gpt-neo` in the name (case sensitive) the Clover will assume that it's using standard GPT-2 based model.

**Comment by Skhmt** [comment]
Is there a better way to detect if a model is gpt-neo or not?

**Comment by AtaIanta** [comment]
Surely there is, @finetuneanon sorry for the ping but this is your code so maybe you know how to do it.

Detecting by folder name seems the easiest though.

**Comment by finetuneanon** [comment]
Went the easy route. Should also be possible to open the config.json and check model_type there.

**Comment by Skhmt** [comment]
Added to readme (and made detection case-insensitive) for now.

**Comment by Skhmt** [comment]
Added 2 checks in config.json for architectures["GPTNeoForCausalLM"] and for model_type == "gpt_neo".  If any of the three conditions are true (including the existing file name check), it'll assume gpt-neo.
