### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by Robo798814** [cloveranon/Clover-Edition#185]
Hi there; I've been trying to get AiDungeon: Clover Edition to run for a while now and so far I have not found any solution anywhere else online. I've tried relaunching the launch.bat software, deleting and reinstalling the whole AiDungeon folder and so far nothing works. Help would be appreciated. 

The following error is specified here: 
```
Traceback (most recent call last):
  File "C:\Users\18138\OneDrive\Desktop\Clover-Edition-master\launch.py", line 1, in <module>
    import aidungeon
  File "C:\Users\18138\OneDrive\Desktop\Clover-Edition-master\aidungeon\__init__.py", line 1, in <module>
    from .play import *
  File "C:\Users\18138\OneDrive\Desktop\Clover-Edition-master\aidungeon\play.py", line 6, in <module>
    from .gpt2generator import GPT2Generator
  File "C:\Users\18138\OneDrive\Desktop\Clover-Edition-master\aidungeon\gpt2generator.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

[process exited with code 1]
```

**Comment by cloveranon** [comment]
It didn't install pytorch. You can try the other installer: https://github.com/AIDungeonWiXAnon/AID2-Installer-Project
or you can manually install python and pytorch

**Comment by Skhmt** [comment]
you might have missed the `pip install -r requirements/cuda_requirements.txt` or `pip install -r requirements/cpu_requirements.txt` step if you didnt use install.bat.
