### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by LeonzeT** [cloveranon/Clover-Edition#209]
This happens every time after I select a model.

`Traceback (most recent call last):
  File "D:\Download\Clover-Edition-master\launch.py", line 1, in <module>
    import aidungeon
  File "D:\Download\Clover-Edition-master\aidungeon\__init__.py", line 61, in <module>
    if gm and gm.story:
NameError: name 'gm' is not defined`

**Comment by Meanmelter** [comment]
Sounds like the model did not download properly. Is this on windows?

**Comment by Austando** [comment]
Hey I'm having what is a similar issue, I'm on Windows 10 and after installing I tried to run on of the models and I got the usual traceback error stuff and I exited out. I read in another post that if you previously had Python installed it could mess with the Install.bat so I uninstalled Python and tried again, now when I try and select either model nothing happens I don't even get an error so naturally I just wanted to see if any of the commands worked so I inputted to for exit and it gave (what I assume is the error i got when I first tried to launch one of the modules which I have a screenshot of here:  
![image](https://user-images.githubusercontent.com/93636158/140012050-6412cdbf-f768-4a2b-8811-5f5bf9ec01e1.png)
any help would be apricated
thanks!
